<?php include '../../includes/head.php';

patternize('A',      '../a.html');
patternize('EM',     '../em.html');
patternize('STRONG', '../strong.html');
patternize('SMALL',  '../small.html');
// patternize('S',      '../s.html');
// patternize('cite',   '../cite.html');
patternize('q',      '../q.html');
// patternize('dfn',    '../dfn.html');
patternize('abbr',   '../abbr.html');
// patternize('ruby',   '../ruby.html');
// patternize('rb',     '../rb.html');
// patternize('rt',     '../rt.html');
// patternize('rtc',    '../rtc.html');
// patternize('rp',     '../rp.html');
// patternize('data',   '../data.html');
// patternize('time',   '../time.html');
// patternize('code',   '../code.html');
// patternize('var',    '../var.html');
// patternize('samp',   '../samp.html');
// patternize('kbd',    '../kbd.html');
patternize('sub',    '../sub.html');
patternize('sup',    '../sup.html');
// patternize('i',      '../i.html');
// patternize('b',      '../b.html');
// patternize('u',      '../u.html');
// patternize('mark',   '../mark.html');
// patternize('bdi',    '../bdi.html');
// patternize('bdo',    '../bdo.html');
// patternize('span',   '../span.html');
// patternize('br',     '../br.html');
// patternize('wbr',    '../wbr.html');

include '../../includes/footer.php';