<?php include '../../includes/head.php' ?>

<?php patternize('A',      '01-a.html'); ?>
<?php patternize('EM',     '02-em.html'); ?>
<?php patternize('STRONG', '03-strong.html'); ?>
<?php patternize('SMALL',  '04-small.html'); ?>
<?php patternize('S',      '05-s.html'); ?>
<?php patternize('cite',   '06-cite.html'); ?>
<?php patternize('q',      '07-q.html'); ?>
<?php patternize('dfn',    '08-dfn.html'); ?>
<?php patternize('abbr',   '09-abbr.html'); ?>
<?php patternize('ruby',   '10-ruby.html'); ?>
<?php patternize('rb',     '11-rb.html'); ?>
<?php patternize('rt',     '12-rt.html'); ?>
<?php patternize('rtc',    '13-rtc.html'); ?>
<?php patternize('rp',     '14-rp.html'); ?>
<?php patternize('data',   '15-data.html'); ?>
<?php patternize('time',   '16-time.html'); ?>
<?php patternize('code',   '17-code.html'); ?>
<?php patternize('var',    '18-var.html'); ?>
<?php patternize('samp',   '19-samp.html'); ?>
<?php patternize('kbd',    '20-kbd.html'); ?>
<?php patternize('sub',    '21.1-sub.html'); ?>
<?php patternize('sup',    '21.2-sup.html'); ?>
<?php patternize('i',      '22-i.html'); ?>
<?php patternize('b',      '23-b.html'); ?>
<?php patternize('u',      '24-u.html'); ?>
<?php patternize('mark',   '25-mark.html'); ?>
<?php patternize('bdi',    '26-bdi.html'); ?>
<?php patternize('bdo',    '27-bdo.html'); ?>
<?php patternize('span',   '28-span.html'); ?>
<?php patternize('br',     '29-br.html'); ?>
<?php patternize('wbr',    '30-wbr.html'); ?>

<?php include '../../includes/footer.php' ?>